### ISSUE TITLE
cut command produces an error on Ubuntu 16.04.2 LTS

### ISSUE THREAD

**Issue by sirmodok** [leonjza/awesome-nmap-grep#1]
The cut command no longer accepts input like this **cut -d' ' -f2 -f4-**
It produces the error **cut: only one type of list may be specified**
To resolve this change the cut command  **cut -d' ' -f2 -f4-** to **cut -d' ' -f2,4-**

**Comment by leonjza** [comment]
Thanks for the heads up!

**Comment by pcastagnaro** [comment]
> The cut command no longer accepts input like this **cut -d' ' -f2 -f4-**
> It produces the error **cut: only one type of list may be specified**
> To resolve this change the cut command **cut -d' ' -f2 -f4-** to **cut -d' ' -f2,4-**

Thanks @sirmodok! With your comment it works great!
![image](https://user-images.githubusercontent.com/8824742/50770003-8772fb80-1264-11e9-92b9-18db774a7743.png)
