### ISSUE TITLE
How did you create the pretty ascii graphic in the #explained section?

### ISSUE THREAD

**Issue by mamachanko** [leonjza/awesome-nmap-grep#3]
This one [here](https://github.com/leonjza/awesome-nmap-grep#explained):

![Screenshot 2020-10-11 at 13 24 33](https://user-images.githubusercontent.com/1182927/95677343-1bee5880-0bc5-11eb-9272-d839b1149534.png)

I am sure there's a tool for that, isn't there? Or is it hand-crafted?

**Comment by leonjza** [comment]
This was hand crafted, but the idea comes from https://explainshell.com/

**Comment by mamachanko** [comment]
Thank you, @leonjza !
