### ISSUE TITLE
Explain Host and Open Ports

### ISSUE THREAD

**Issue by iAmG-r00t** [leonjza/awesome-nmap-grep#4]
Hey, kindly could you explain this [part](https://github.com/leonjza/awesome-nmap-grep#hosts-and-open-ports), mostly the awk bit would love to understand how you did it so that I can edit it for it to output host-ip port service portocol.

**Comment by iAmG-r00t** [comment]
@leonjza please do help here!!

**Comment by leonjza** [comment]
Sorry, I am just spread too thin at the moment to dive into the details here. The best advice I can give is to checkout `man awk` for details about the syntax.
